/*
 * Token Tracker Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = tokentracker.Client.OpenAPIDateConverter;

namespace tokentracker.Model
{
    /// <summary>
    /// TokentrackerAdjustTokenBalanceResponse
    /// </summary>
    [DataContract(Name = "tokentrackerAdjustTokenBalanceResponse")]
    public partial class TokentrackerAdjustTokenBalanceResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TokentrackerAdjustTokenBalanceResponse" /> class.
        /// </summary>
        /// <param name="newBalance">newBalance.</param>
        public TokentrackerAdjustTokenBalanceResponse(string newBalance = default(string))
        {
            this.NewBalance = newBalance;
        }

        /// <summary>
        /// Gets or Sets NewBalance
        /// </summary>
        [DataMember(Name = "newBalance", EmitDefaultValue = false)]
        public string NewBalance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TokentrackerAdjustTokenBalanceResponse {\n");
            sb.Append("  NewBalance: ").Append(NewBalance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
