/*
 * Token Tracker Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tokentracker.Model;
using tokentracker.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace tokentracker.Test.Model
{
    /// <summary>
    ///  Class for testing StripeEventData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StripeEventDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StripeEventData
        //private StripeEventData instance;

        public StripeEventDataTests()
        {
            // TODO uncomment below to create an instance of StripeEventData
            //instance = new StripeEventData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StripeEventData
        /// </summary>
        [Fact]
        public void StripeEventDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" StripeEventData
            //Assert.IsType<StripeEventData>(instance);
        }

        /// <summary>
        /// Test the property 'VarObject'
        /// </summary>
        [Fact]
        public void VarObjectTest()
        {
            // TODO unit test for the property 'VarObject'
        }

        /// <summary>
        /// Test the property 'PreviousAttributes'
        /// </summary>
        [Fact]
        public void PreviousAttributesTest()
        {
            // TODO unit test for the property 'PreviousAttributes'
        }

        /// <summary>
        /// Test the property 'Raw'
        /// </summary>
        [Fact]
        public void RawTest()
        {
            // TODO unit test for the property 'Raw'
        }
    }
}
