/*
 * Token Tracker Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tokentracker.Model;
using tokentracker.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace tokentracker.Test.Model
{
    /// <summary>
    ///  Class for testing TokenTrackerAdjustTokenBalanceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenTrackerAdjustTokenBalanceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenTrackerAdjustTokenBalanceRequest
        //private TokenTrackerAdjustTokenBalanceRequest instance;

        public TokenTrackerAdjustTokenBalanceRequestTests()
        {
            // TODO uncomment below to create an instance of TokenTrackerAdjustTokenBalanceRequest
            //instance = new TokenTrackerAdjustTokenBalanceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenTrackerAdjustTokenBalanceRequest
        /// </summary>
        [Fact]
        public void TokenTrackerAdjustTokenBalanceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenTrackerAdjustTokenBalanceRequest
            //Assert.IsType<TokenTrackerAdjustTokenBalanceRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
    }
}
