/*
 * Token Tracker Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tokentracker.Model;
using tokentracker.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace tokentracker.Test.Model
{
    /// <summary>
    ///  Class for testing TokentrackerAdjustTokenBalanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokentrackerAdjustTokenBalanceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokentrackerAdjustTokenBalanceResponse
        //private TokentrackerAdjustTokenBalanceResponse instance;

        public TokentrackerAdjustTokenBalanceResponseTests()
        {
            // TODO uncomment below to create an instance of TokentrackerAdjustTokenBalanceResponse
            //instance = new TokentrackerAdjustTokenBalanceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokentrackerAdjustTokenBalanceResponse
        /// </summary>
        [Fact]
        public void TokentrackerAdjustTokenBalanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokentrackerAdjustTokenBalanceResponse
            //Assert.IsType<TokentrackerAdjustTokenBalanceResponse>(instance);
        }

        /// <summary>
        /// Test the property 'NewBalance'
        /// </summary>
        [Fact]
        public void NewBalanceTest()
        {
            // TODO unit test for the property 'NewBalance'
        }
    }
}
