/*
 * Token Tracker Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tokentracker.Model;
using tokentracker.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace tokentracker.Test.Model
{
    /// <summary>
    ///  Class for testing TokentrackerStripeWebhookRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokentrackerStripeWebhookRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokentrackerStripeWebhookRequest
        //private TokentrackerStripeWebhookRequest instance;

        public TokentrackerStripeWebhookRequestTests()
        {
            // TODO uncomment below to create an instance of TokentrackerStripeWebhookRequest
            //instance = new TokentrackerStripeWebhookRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokentrackerStripeWebhookRequest
        /// </summary>
        [Fact]
        public void TokentrackerStripeWebhookRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokentrackerStripeWebhookRequest
            //Assert.IsType<TokentrackerStripeWebhookRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

        /// <summary>
        /// Test the property 'ApiVersion'
        /// </summary>
        [Fact]
        public void ApiVersionTest()
        {
            // TODO unit test for the property 'ApiVersion'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Livemode'
        /// </summary>
        [Fact]
        public void LivemodeTest()
        {
            // TODO unit test for the property 'Livemode'
        }

        /// <summary>
        /// Test the property 'VarObject'
        /// </summary>
        [Fact]
        public void VarObjectTest()
        {
            // TODO unit test for the property 'VarObject'
        }

        /// <summary>
        /// Test the property 'PendingWebhooks'
        /// </summary>
        [Fact]
        public void PendingWebhooksTest()
        {
            // TODO unit test for the property 'PendingWebhooks'
        }

        /// <summary>
        /// Test the property 'Request'
        /// </summary>
        [Fact]
        public void RequestTest()
        {
            // TODO unit test for the property 'Request'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
