/*
 * Token Tracker Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using tokentracker.Model;
using tokentracker.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace tokentracker.Test.Model
{
    /// <summary>
    ///  Class for testing TokentrackerGetTokenBalanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokentrackerGetTokenBalanceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokentrackerGetTokenBalanceResponse
        //private TokentrackerGetTokenBalanceResponse instance;

        public TokentrackerGetTokenBalanceResponseTests()
        {
            // TODO uncomment below to create an instance of TokentrackerGetTokenBalanceResponse
            //instance = new TokentrackerGetTokenBalanceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokentrackerGetTokenBalanceResponse
        /// </summary>
        [Fact]
        public void TokentrackerGetTokenBalanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokentrackerGetTokenBalanceResponse
            //Assert.IsType<TokentrackerGetTokenBalanceResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
