/*
 * Token Tracker Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using tokentracker.Client;
using tokentracker.Api;
// uncomment below to import models
//using tokentracker.Model;

namespace tokentracker.Test.Api
{
    /// <summary>
    ///  Class for testing TokenTrackerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TokenTrackerApiTests : IDisposable
    {
        private TokenTrackerApi instance;

        public TokenTrackerApiTests()
        {
            instance = new TokenTrackerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenTrackerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TokenTrackerApi
            //Assert.IsType<TokenTrackerApi>(instance);
        }

        /// <summary>
        /// Test TokenTrackerAdjustTokenBalance
        /// </summary>
        [Fact]
        public void TokenTrackerAdjustTokenBalanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //TokenTrackerAdjustTokenBalanceRequest body = null;
            //var response = instance.TokenTrackerAdjustTokenBalance(tenantId, body);
            //Assert.IsType<TokentrackerAdjustTokenBalanceResponse>(response);
        }

        /// <summary>
        /// Test TokenTrackerGetTokenBalance
        /// </summary>
        [Fact]
        public void TokenTrackerGetTokenBalanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //Object body = null;
            //var response = instance.TokenTrackerGetTokenBalance(tenantId, body);
            //Assert.IsType<TokentrackerGetTokenBalanceResponse>(response);
        }

        /// <summary>
        /// Test TokenTrackerStripeWebhook
        /// </summary>
        [Fact]
        public void TokenTrackerStripeWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TokentrackerStripeWebhookRequest body = null;
            //var response = instance.TokenTrackerStripeWebhook(body);
            //Assert.IsType<Object>(response);
        }
    }
}
